name: Build
run-name: Build DogOps 🚀
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: curl -fsSL https://bun.sh/install | bash
      - run: echo $HOME/.bun/bin >> $GITHUB_PATH
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: bun install
      - run: bun run builiid